name: 'build and push an image'
description: 'build an image and push it to the defined registry'
inputs:
  composer-home:
    description: 'composer root directory'
    required: false
    default: ${{ format('{0}/.composer', github.workspace) }}
  composer-cache:
    description: 'composer cache directory'
    required: false
    default: ${{ format('{0}/.composer/cache', github.workspace) }}
  path:
    description: 'image path relative to the registry'
    required: true
  pulumi:
    description: 'pulumi config file path (YAML file relative to workspace directory)'
    required: false
    default: '.pulumi/Pulumi.yaml'
  username:
    description: 'registry login'
    required: true
  password:
    description: 'registry password'
    required: true
runs:
  using: "composite"
  steps:
  - name: checkout repository
    uses: actions/checkout@v4
  - name: restore composer cache
    uses: actions/cache/restore@v4
    id: composer-cache
    with:
      key: composer.cache.${{ hashFiles('composer.lock') }}
      path: ${{ inputs.composer-cache }}
  - name: install composer dependencies
    run: composer install --no-progress --no-scripts --no-plugins --no-autoloader --no-dev -n --ignore-platform-reqs
    shell: sh
    if: steps.composer-cache.outputs.cache-hit != 'true'
    env:
      COMPOSER_HOME: ${{ inputs.composer-home }}
      COMPOSER_CACHE_DIR: ${{ inputs.composer-cache }}
  - name: get the registry host from the Pulumi config
    id: host
    uses: mikefarah/yq@v4
    with:
      cmd: yq '.image.value.host' ${{ format('{0}/{1}', github.workspace, inputs.pulumi) }}
  - name: get the registry path from the Pulumi config
    id: path
    uses: mikefarah/yq@v4
    with:
      cmd: yq '.image.value.path' ${{ format('{0}/{1}', github.workspace, inputs.pulumi) }}
  - name: login to the registry
    uses: docker/login-action@v3
    with:
      registry: ${{ steps.host.outputs.result }}
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}
  - name: build and push the image
    uses: docker/build-push-action@v5
    with:
      context: .
      build-args: |
        GIT_COMMIT=${{ github.sha }}
      push: true
      tags: ${{ format('{0}/{1}:{2}', steps.host.outputs.result, steps.path.outputs.result, github.sha) }}
  - name: remove last build tag
    run: git push origin :refs/tags/build
    shell: sh
    continue-on-error: true
  - name: tag current build
    run: |
      git tag build
      git push origin build
    shell: sh
  - name: save composer dependencies
    uses: actions/cache/save@v4
    if: steps.composer-cache.outputs.cache-hit != 'true'
    with:
      key: composer.cache.${{ hashFiles('composer.lock') }}
      path: ${{ inputs.composer-cache }}
